# Start with a base image
FROM python:3.9-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app
COPY requirements.dev.txt /app

# Install the required packages
RUN apk update \
    && apk add --no-cache postgresql-dev \
    && apk add --no-cache --virtual .build-deps gcc musl-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && if [ "$DEV" = "true" ]; then pip install --no-cache-dir -r requirements.dev.txt; fi \
    && apk del .build-deps

# Copy the project code into the container
COPY ./app /app

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose the default port used by Django
EXPOSE 8000




# FROM python:3.9-alpine3.13
# LABEL maintainer="aibaribray"

# ENV PYTHONUNBUFFERED 1

# COPY ./requirements.txt /tmp/requirements.txt
# COPY ./app /app
# WORKDIR /app
# EXPOSE 8000

# RUN python -m venv /py && \
#     /py/bin/pip install --upgrade pip && \
#     /py/bin/pip install -r /tmp/requirements.txt && \
#     rm -rf /tmp && \
#     adduser \
#         --disabled-password \
#         --no-create-home \
#         django-user

# ENV PATH="/py/bin:$PATH"

# USER django-user