# Start with a base image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app
COPY requirements.dev.txt /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Install additional packages if DEV argument is true
ARG DEV=false
RUN if [ "$DEV" = "true" ]; then pip install --no-cache-dir -r requirements.dev.txt; fi

# Copy the project code into the container
COPY . /app

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose the default port used by Django
EXPOSE 8000

# Run the migrations
# RUN python manage.py makemigrations
# RUN python manage.py migrate

# Run the Django server
CMD python manage.py runserver 0.0.0.0:8000




# FROM python:3.9-alpine3.13
# LABEL maintainer="aibaribray"

# ENV PYTHONUNBUFFERED 1

# COPY ./requirements.txt /tmp/requirements.txt
# COPY ./app /app
# WORKDIR /app
# EXPOSE 8000

# RUN python -m venv /py && \
#     /py/bin/pip install --upgrade pip && \
#     /py/bin/pip install -r /tmp/requirements.txt && \
#     rm -rf /tmp && \
#     adduser \
#         --disabled-password \
#         --no-create-home \
#         django-user

# ENV PATH="/py/bin:$PATH"

# USER django-user